
#line 2 "<stdout>"

#define YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN (-32767 - 1)
#endif
#ifndef INT32_MIN
#define INT32_MIN (-2147483647 - 1)
#endif
#ifndef INT8_MAX
#define INT8_MAX (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR)(c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start)-1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n)                                                                               \
    do {                                                                                        \
        /* Undo effects of setting up yytext. */                                                \
        int yyless_macro_arg = (n);                                                             \
        YY_LESS_LINENO(yyless_macro_arg);                                                       \
        *yy_cp = (yy_hold_char);                                                                \
        YY_RESTORE_YY_MORE_OFFSET(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */                                          \
    } while (0)
#define unput(c) yyunput(c, (yytext_ptr))

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state {
    FILE* yy_input_file;

    char* yy_ch_buf; /* input buffer */
    char* yy_buf_pos; /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
    int yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
    int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

    /* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
    int yy_fill_buffer;

    int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE* yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ((yy_buffer_stack)       \
        ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
        : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars; /* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char* yy_c_buf_p = NULL;
static int yy_init = 0; /* whether we need to initialize */
static int yy_start = 0; /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart(FILE* input_file);
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy_create_buffer(FILE* file, int size);
void yy_delete_buffer(YY_BUFFER_STATE b);
void yy_flush_buffer(YY_BUFFER_STATE b);
void yypush_buffer_state(YY_BUFFER_STATE new_buffer);
void yypop_buffer_state(void);

static void yyensure_buffer_stack(void);
static void yy_load_buffer_state(void);
static void yy_init_buffer(YY_BUFFER_STATE b, FILE* file);
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)

YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size);
YY_BUFFER_STATE yy_scan_string(const char* yy_str);
YY_BUFFER_STATE yy_scan_bytes(const char* bytes, int len);

void* yyalloc(yy_size_t);
void* yyrealloc(void*, yy_size_t);
void yyfree(void*);

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)                                  \
    {                                                                       \
        if (!YY_CURRENT_BUFFER) {                                           \
            yyensure_buffer_stack();                                        \
            YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE); \
        }                                                                   \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive;       \
    }
#define yy_set_bol(at_bol)                                                  \
    {                                                                       \
        if (!YY_CURRENT_BUFFER) {                                           \
            yyensure_buffer_stack();                                        \
            YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE); \
        }                                                                   \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol;                       \
    }
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char* yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state(void);
static yy_state_type yy_try_NUL_trans(yy_state_type current_state);
static int yy_get_next_buffer(void);
static void yynoreturn yy_fatal_error(const char* msg);

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION        \
    (yytext_ptr) = yy_bp;          \
    yyleng = (int)(yy_cp - yy_bp); \
    (yy_hold_char) = *yy_cp;       \
    *yy_cp = '\0';                 \
    (yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info {
    flex_int32_t yy_verify;
    flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[74] = { 0,
    0, 0, 0, 0, 0, 0, 18, 17, 15, 1,
    1, 15, 15, 15, 15, 15, 4, 4, 4, 2,
    2, 10, 11, 16, 16, 16, 1, 0, 12, 0,
    0, 0, 0, 4, 4, 4, 0, 3, 13, 3,
    4, 4, 8, 0, 6, 8, 0, 8, 2, 2,
    2, 2, 14, 12, 9, 0, 0, 3, 0, 0,
    3, 7, 5, 0, 0, 3, 0, 0, 3, 3,
    0, 3, 0 };

static const YY_CHAR yy_ec[256] = { 0,
    1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 2, 1, 4, 1, 1, 1, 1, 5, 1,
    1, 6, 7, 1, 7, 8, 9, 10, 11, 11,
    11, 11, 11, 11, 11, 12, 12, 13, 1, 1,
    1, 1, 1, 1, 14, 15, 15, 14, 16, 14,
    17, 18, 17, 17, 17, 17, 17, 17, 19, 17,
    17, 17, 17, 17, 17, 17, 17, 20, 17, 17,
    21, 22, 23, 24, 1, 1, 14, 15, 15, 14,

    16, 14, 17, 18, 17, 17, 17, 17, 17, 17,
    19, 17, 17, 17, 17, 17, 17, 17, 17, 20,
    17, 17, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1 };

static const YY_CHAR yy_meta[25] = { 0,
    1, 1, 1, 1, 1, 1, 2, 1, 1, 3,
    3, 3, 4, 5, 5, 6, 4, 4, 4, 4,
    1, 1, 1, 1 };

static const flex_int16_t yy_base[85] = { 0,
    0, 0, 0, 0, 19, 20, 188, 204, 204, 28,
    30, 23, 165, 41, 24, 130, 50, 18, 61, 71,
    122, 204, 204, 204, 123, 122, 37, 37, 204, 45,
    116, 89, 95, 104, 23, 115, 63, 94, 204, 82,
    0, 0, 0, 127, 204, 37, 0, 204, 0, 204,
    84, 81, 204, 73, 204, 91, 86, 47, 47, 93,
    43, 68, 0, 101, 97, 130, 37, 133, 136, 139,
    142, 145, 204, 157, 163, 169, 175, 179, 183, 187,
    191, 196, 198, 200 };

static const flex_int16_t yy_def[85] = { 0,
    74, 74, 73, 3, 75, 75, 73, 73, 73, 73,
    73, 76, 77, 73, 73, 73, 73, 17, 18, 73,
    78, 73, 73, 73, 73, 73, 73, 76, 73, 76,
    73, 73, 77, 73, 34, 73, 36, 79, 73, 80,
    18, 19, 37, 37, 73, 73, 81, 73, 20, 73,
    78, 78, 73, 76, 73, 73, 82, 80, 83, 73,
    44, 73, 81, 73, 73, 73, 84, 73, 73, 73,
    73, 73, 0, 73, 73, 73, 73, 73, 73, 73,
    73, 73, 73, 73 };

static const flex_int16_t yy_nxt[229] = { 0,
    9, 10, 11, 12, 13, 9, 14, 15, 16, 17,
    18, 19, 9, 20, 20, 20, 21, 21, 21, 21,
    22, 9, 23, 9, 25, 25, 29, 26, 26, 27,
    27, 27, 27, 38, 38, 38, 48, 73, 27, 27,
    29, 48, 73, 71, 30, 33, 62, 62, 54, 73,
    34, 35, 36, 68, 37, 37, 37, 40, 30, 41,
    41, 42, 67, 37, 43, 44, 30, 45, 46, 47,
    42, 42, 37, 37, 37, 37, 29, 62, 62, 73,
    49, 49, 49, 50, 49, 49, 49, 51, 52, 51,
    51, 31, 65, 50, 30, 55, 50, 59, 56, 56,

    64, 64, 70, 70, 70, 55, 66, 66, 66, 57,
    31, 31, 31, 35, 35, 36, 32, 37, 43, 37,
    55, 45, 46, 47, 36, 36, 36, 39, 37, 37,
    37, 53, 45, 60, 50, 39, 61, 61, 61, 66,
    66, 66, 69, 69, 69, 69, 69, 69, 70, 70,
    70, 72, 72, 72, 72, 72, 72, 8, 8, 8,
    8, 8, 8, 24, 24, 24, 24, 24, 24, 28,
    28, 28, 28, 28, 28, 31, 31, 31, 31, 31,
    31, 51, 51, 51, 51, 38, 32, 73, 38, 58,
    73, 73, 58, 63, 73, 63, 63, 66, 66, 69,

    69, 72, 72, 7, 73, 73, 73, 73, 73, 73,
    73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
    73, 73, 73, 73, 73, 73, 73, 73 };

static const flex_int16_t yy_chk[229] = { 0,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 5, 6, 12, 5, 6, 10,
    10, 11, 11, 15, 15, 15, 18, 18, 27, 27,
    28, 35, 35, 67, 12, 14, 46, 46, 30, 61,
    14, 14, 14, 59, 14, 14, 14, 17, 28, 17,
    17, 17, 58, 17, 17, 17, 30, 17, 17, 17,
    19, 19, 37, 37, 37, 19, 54, 62, 62, 19,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 32, 57, 52, 54, 56, 51, 40, 32, 32,

    56, 56, 60, 60, 60, 64, 65, 65, 65, 38,
    64, 64, 32, 34, 34, 34, 33, 34, 34, 34,
    31, 34, 34, 34, 36, 36, 36, 26, 36, 36,
    36, 25, 36, 44, 21, 16, 44, 44, 44, 66,
    66, 66, 68, 68, 68, 69, 69, 69, 70, 70,
    70, 71, 71, 71, 72, 72, 72, 74, 74, 74,
    74, 74, 74, 75, 75, 75, 75, 75, 75, 76,
    76, 76, 76, 76, 76, 77, 77, 77, 77, 77,
    77, 78, 78, 78, 78, 79, 13, 7, 79, 80,
    0, 0, 80, 81, 0, 81, 81, 82, 82, 83,

    83, 84, 84, 73, 73, 73, 73, 73, 73, 73,
    73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
    73, 73, 73, 73, 73, 73, 73, 73 };

static yy_state_type yy_last_accepting_state;
static char* yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char* yytext;
#line 1 "lexer.l"
/*************************************************************
Copyright (C) 1990, 1991, 1993 Andy C. Hung, all rights reserved.
PUBLIC DOMAIN LICENSE: Stanford University Portable Video Research
Group. If you use this software, you agree to the following: This
program package is purely experimental, and is licensed "as is".
Permission is granted to use, modify, and distribute this program
without charge for any purpose, provided this license/ disclaimer
notice appears in the copies.  No warranty or maintenance is given,
either expressed or implied.  In no event shall the author(s) be
liable to you or a third party for any special, incidental,
consequential, or other damages, arising out of the use or inability
to use the program for any purpose (or the loss of data), even if we
have been advised of such possibilities.  Any public reference or
advertisement of this source code should refer to it as the Portable
Video Research Group (PVRG) code, and not by any author(s) (or
Stanford University) name.
*************************************************************/
#line 19 "lexer.l"

/*LABEL lexer.c */

/* Redefine the yywrap so that we don't have
   to worry about lex library */
#define YY_SKIP_YYWRAP
#define yywrap() (1)

static char* ReservedWords[] = {
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "NOT",
    "AND",
    "OR",
    "XOR",
    "LT",
    "LTE",
    "EQ",
    "GT",
    "GTE",
    "NEG",
    "SQRT",
    "ABS",
    "FLOOR",
    "CEIL",
    "ROUND",
    "DUP",
    "POP",
    "EXCH",
    "COPY",
    "ROLL",
    "INDEX",
    "CLEAR",
    "STO",
    "RCL",
    "GOTO",
    "IFG",
    "IFNG",
    "EXIT",
    "EXE",
    "ABORT",
    "PRINTSTACK",
    "PRINTPROGRAM",
    "PRINTIMAGE",
    "PRINTFRAME",
    "ECHO",
    "OPEN",
    "CLOSE",
    "EQU",
    "VAL",
    "STREAMNAME",
    "COMPONENT",
    "FRAMERATE",
    "FRAMESKIP",
    "QUANTIZATION",
    "SEARCHLIMIT",
    "NTSC",
    "CIF",
    "QCIF",
    ""
};

#define R_ADD 1
#define R_SUB 2
#define R_MUL 3
#define R_DIV 4
#define R_NOT 5
#define R_AND 6
#define R_OR 7
#define R_XOR 8
#define R_LT 9
#define R_LTE 10
#define R_EQ 11
#define R_GT 12
#define R_GTE 13
#define R_NEG 14
#define R_SQRT 15
#define R_ABS 16
#define R_FLOOR 17
#define R_CEIL 18
#define R_ROUND 19
#define R_DUP 20
#define R_POP 21
#define R_EXCH 22
#define R_COPY 23
#define R_ROLL 24
#define R_INDEX 25
#define R_CLEAR 26
#define R_STO 27
#define R_RCL 28
#define R_GOTO 29
#define R_IFG 30
#define R_IFNG 31
#define R_EXIT 32
#define R_EXE 33
#define R_ABORT 34
#define R_PRINTSTACK 35
#define R_PRINTPROGRAM 36
#define R_PRINTIMAGE 37
#define R_PRINTFRAME 38
#define R_ECHO 39
#define R_OPEN 40
#define R_CLOSE 41
#define R_EQU 42
#define R_VAL 43
#define R_STREAMNAME 44
#define R_COMPONENT 45
#define R_FRAMERATE 46
#define R_FRAMESKIP 47
#define R_QUANTIZATION 48
#define R_SEARCHLIMIT 49
#define R_NTSC 50
#define R_CIF 51
#define R_QCIF 52

#define R_INTEGER 1000
#define R_LBRACKET 1001
#define R_RBRACKET 1002
#define R_ID 1003
#define R_STRING 1004
#define R_REAL 1005

static char* EquLabels[] = {
    "GQUANT",
    "MQUANT",
    "MQUANTENABLE",
    "MTYPE",
    "BD",
    "DBD",
    "VAROR",
    "VAR",
    "MWOR",
    "RATE",
    "BUFFERSIZE",
    "BUFFERCONTENTS",
    "QDFACT",
    "QOFFS",
    ""
};

#define L_GQUANT 1
#define L_MQUANT 2
#define L_MQUANTENABLE 3
#define L_MTYPE 4
#define L_BD 5
#define L_DBD 6
#define L_VAROR 7
#define L_VAR 8
#define L_MWOR 9
#define L_RATE 10
#define L_BUFFERSIZE 11
#define L_BUFFERCONTENTS 12
#define L_QDFACT 13
#define L_QOFFS 14

int CommentDepth = 0; /* depth of comment nesting */
int yyint = 0; /* Return value for integers */
int LexDebug = 0; /* Status of lex debugging */

#define PRIME 211
#define EOS '\0'

#define MakeStructure(S) (S*)malloc(sizeof(S))
#define InsertLink(link, list) \
    {                          \
        if (!list) {           \
            list = link;       \
        } else {               \
            link->next = list; \
            list = link;       \
        }                      \
    }

#define ID struct id
#define LINK struct link_def
ID
{ /* Default id structure */
    char* name;
    int tokentype;
    int count;
    int value;
};

LINK
{ /* A link for the hash buckets */
    ID* lid;
    LINK* next;
};

ID* Cid = NULL;

/*PUBLIC*/

extern void initparser();
extern void parser();
extern void Execute();

static int hashpjw();
static LINK* MakeLink();
static ID* enter();
static char* getstr();
static void PrintProgram();
static void MakeProgram();
static void CompileProgram();
static int mylex();

/*PRIVATE*/

/*NOPROTO*/

#line 734 "<stdout>"

#line 736 "<stdout>"

#define INITIAL 0
#define NORMAL 1
#define COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void*
#endif

static int yy_init_globals(void);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy(void);

int yyget_debug(void);

void yyset_debug(int debug_flag);

YY_EXTRA_TYPE yyget_extra(void);

void yyset_extra(YY_EXTRA_TYPE user_defined);

FILE* yyget_in(void);

void yyset_in(FILE* _in_str);

FILE* yyget_out(void);

void yyset_out(FILE* _out_str);

int yyget_leng(void);

char* yyget_text(void);

int yyget_lineno(void);

void yyset_lineno(int _line_number);

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap(void);
#else
extern int yywrap(void);
#endif
#endif

#ifndef YY_NO_UNPUT

static void yyunput(int c, char* buf_ptr);

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy(char*, const char*, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char*);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void);
#else
static int input(void);
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO                                            \
    do {                                                \
        if (fwrite(yytext, (size_t)yyleng, 1, yyout)) { \
        }                                               \
    } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)                                                         \
    if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) {                                          \
        int c = '*';                                                                            \
        int n;                                                                                  \
        for (n = 0; n < max_size && (c = getc(yyin)) != EOF && c != '\n'; ++n)                  \
            buf[n] = (char)c;                                                                   \
        if (c == '\n')                                                                          \
            buf[n++] = (char)c;                                                                 \
        if (c == EOF && ferror(yyin))                                                           \
            YY_FATAL_ERROR("input in flex scanner failed");                                     \
        result = n;                                                                             \
    } else {                                                                                    \
        errno = 0;                                                                              \
        while ((result = (int)fread(buf, 1, (yy_size_t)max_size, yyin)) == 0 && ferror(yyin)) { \
            if (errno != EINTR) {                                                               \
                YY_FATAL_ERROR("input in flex scanner failed");                                 \
                break;                                                                          \
            }                                                                                   \
            errno = 0;                                                                          \
            clearerr(yyin);                                                                     \
        }                                                                                       \
    }

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex(void);

#define YY_DECL int yylex(void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/ break;
#endif

#define YY_RULE_SETUP \
    YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
    yy_state_type yy_current_state;
    char *yy_cp, *yy_bp;
    int yy_act;

    if (!(yy_init)) {
        (yy_init) = 1;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if (!(yy_start))
            (yy_start) = 1; /* first start state */

        if (!yyin)
            yyin = stdin;

        if (!yyout)
            yyout = stdout;

        if (!YY_CURRENT_BUFFER) {
            yyensure_buffer_stack();
            YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
        }

        yy_load_buffer_state();
    }

    {
#line 245 "lexer.l"

#line 958 "<stdout>"

        while (/*CONSTCOND*/ 1) /* loops until end-of-file is reached */
        {
            yy_cp = (yy_c_buf_p);

            /* Support of yytext. */
            *yy_cp = (yy_hold_char);

            /* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
            yy_bp = yy_cp;

            yy_current_state = (yy_start);
        yy_match:
            do {
                YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
                if (yy_accept[yy_current_state]) {
                    (yy_last_accepting_state) = yy_current_state;
                    (yy_last_accepting_cpos) = yy_cp;
                }
                while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
                    yy_current_state = (int)yy_def[yy_current_state];
                    if (yy_current_state >= 74)
                        yy_c = yy_meta[yy_c];
                }
                yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
                ++yy_cp;
            } while (yy_base[yy_current_state] != 204);

        yy_find_action:
            yy_act = yy_accept[yy_current_state];
            if (yy_act == 0) { /* have to back up */
                yy_cp = (yy_last_accepting_cpos);
                yy_current_state = (yy_last_accepting_state);
                yy_act = yy_accept[yy_current_state];
            }

            YY_DO_BEFORE_ACTION;

        do_action: /* This label is used only to access EOF actions. */

            switch (yy_act) { /* beginning of action switch */
            case 0: /* must back up */
                /* undo the effects of YY_DO_BEFORE_ACTION */
                *yy_cp = (yy_hold_char);
                yy_cp = (yy_last_accepting_cpos);
                yy_current_state = (yy_last_accepting_state);
                goto yy_find_action;

            case 1:
                /* rule 1 can match eol */
                YY_RULE_SETUP
#line 247 "lexer.l"
                {
                }
                YY_BREAK
            case 2:
                YY_RULE_SETUP
#line 249 "lexer.l"
                {
                    Cid = enter(0, yytext, yyleng);
                    if (LexDebug) {
                        printf("%s : %s (%d)\n",
                            yytext,
                            ((Cid->tokentype) ? "RESERVED" : "IDENTIFIER"),
                            Cid->count);
                    }
                    if (Cid->tokentype) {
                        return (Cid->tokentype);
                    } else {
                        yyint = Cid->value;
                        return (R_ID);
                    }
                }
                YY_BREAK
            case 3:
                YY_RULE_SETUP
#line 267 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "REAL");
                    }
                    return (R_REAL);
                }
                YY_BREAK
            case 4:
                YY_RULE_SETUP
#line 273 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "INTEGER");
                    }
                    yyint = atoi(yytext);
                    return (R_INTEGER);
                }
                YY_BREAK
            case 5:
                YY_RULE_SETUP
#line 279 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "(HEX)INTEGER");
                    }
                    yyint = strtol(yytext + 2, NULL, 16);
                    return (R_INTEGER);
                }
                YY_BREAK
            case 6:
                YY_RULE_SETUP
#line 285 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "(HEX)INTEGER");
                    }
                    yyint = strtol(yytext, NULL, 16);
                    return (R_INTEGER);
                }
                YY_BREAK
            case 7:
                YY_RULE_SETUP
#line 291 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "(OCT)INTEGER");
                    }
                    yyint = strtol(yytext + 2, NULL, 8);
                    return (R_INTEGER);
                }
                YY_BREAK
            case 8:
                YY_RULE_SETUP
#line 297 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "(OCT)INTEGER");
                    }
                    yyint = strtol(yytext, NULL, 8);
                    return (R_INTEGER);
                }
                YY_BREAK
            case 9:
                /* rule 9 can match eol */
                YY_RULE_SETUP
#line 303 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "(CHAR)INTEGER");
                    }
                    if (yyleng > 4) {
                        yyint = strtol(yytext + 2, NULL, 8);
                    } else {
                        if (*(yytext + 1) == '\\') {
                            switch (*(yytext + 2)) {
                            case '0':
                                yyint = 0;
                                break;
                            case 'b':
                                yyint = 0x8;
                                break;
                            case 'i':
                                yyint = 0x9;
                                break;
                            case 'n':
                                yyint = 0xa;
                                break;
                            case 'v':
                                yyint = 0xb;
                                break;
                            case 'f':
                                yyint = 0xc;
                                break;
                            case 'r':
                                yyint = 0xd;
                                break;
                            default:
                                yyint = (*yytext + 2);
                                break;
                            }
                        } else {
                            yyint = *(yytext + 1);
                        }
                    }
                    return (R_INTEGER);
                }
                YY_BREAK
            case 10:
                YY_RULE_SETUP
#line 349 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "LBRACKET");
                    }
                    return (R_LBRACKET);
                }
                YY_BREAK
            case 11:
                YY_RULE_SETUP
#line 354 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "RBRACKET");
                    }
                    return (R_RBRACKET);
                }
                YY_BREAK
            case 12:
                /* rule 12 can match eol */
                YY_RULE_SETUP
#line 359 "lexer.l"
                {
                    if (LexDebug) {
                        printf("%s : %s\n", yytext, "STRING");
                    }
                    return (R_STRING);
                }
                YY_BREAK
            case 13:
                YY_RULE_SETUP
#line 365 "lexer.l"
                {
                    CommentDepth++;
                    BEGIN COMMENT;
                }
                YY_BREAK
            case 14:
                YY_RULE_SETUP
#line 367 "lexer.l"
                {
                    CommentDepth--;
                    if (!CommentDepth)
                        BEGIN NORMAL;
                }
                YY_BREAK
            case 15:
                YY_RULE_SETUP
#line 369 "lexer.l"
                {
                    /* None of the above rules applicable, so
			       it's a bad symbol. */
                    printf("Bad input char '%c' on line %d\n",
                        yytext[0],
                        yylineno);
                }
                YY_BREAK
            case 16:
                /* rule 16 can match eol */
                YY_RULE_SETUP
#line 377 "lexer.l"
                {
                } /*Everything's AOK */
                YY_BREAK
            case 17:
                YY_RULE_SETUP
#line 379 "lexer.l"
                ECHO;
                YY_BREAK
#line 1214 "<stdout>"
            case YY_STATE_EOF(INITIAL):
            case YY_STATE_EOF(NORMAL):
            case YY_STATE_EOF(COMMENT):
                yyterminate();

            case YY_END_OF_BUFFER: {
                /* Amount of text matched not including the EOB char. */
                int yy_amount_of_matched_text = (int)(yy_cp - (yytext_ptr)) - 1;

                /* Undo the effects of YY_DO_BEFORE_ACTION. */
                *yy_cp = (yy_hold_char);
                YY_RESTORE_YY_MORE_OFFSET

                if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW) {
                    /* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
                    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                    YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                    YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                }

                /* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
                if ((yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)]) { /* This was really a NUL. */
                    yy_state_type yy_next_state;

                    (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

                    yy_current_state = yy_get_previous_state();

                    /* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

                    yy_next_state = yy_try_NUL_trans(yy_current_state);

                    yy_bp = (yytext_ptr) + YY_MORE_ADJ;

                    if (yy_next_state) {
                        /* Consume the NUL. */
                        yy_cp = ++(yy_c_buf_p);
                        yy_current_state = yy_next_state;
                        goto yy_match;
                    }

                    else {
                        yy_cp = (yy_c_buf_p);
                        goto yy_find_action;
                    }
                }

                else
                    switch (yy_get_next_buffer()) {
                    case EOB_ACT_END_OF_FILE: {
                        (yy_did_buffer_switch_on_eof) = 0;

                        if (yywrap()) {
                            /* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
                            (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

                            yy_act = YY_STATE_EOF(YY_START);
                            goto do_action;
                        }

                        else {
                            if (!(yy_did_buffer_switch_on_eof))
                                YY_NEW_FILE;
                        }
                        break;
                    }

                    case EOB_ACT_CONTINUE_SCAN:
                        (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

                        yy_current_state = yy_get_previous_state();

                        yy_cp = (yy_c_buf_p);
                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                        goto yy_match;

                    case EOB_ACT_LAST_MATCH:
                        (yy_c_buf_p) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

                        yy_current_state = yy_get_previous_state();

                        yy_cp = (yy_c_buf_p);
                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                        goto yy_find_action;
                    }
                break;
            }

            default:
                YY_FATAL_ERROR(
                    "fatal flex scanner internal error--no action found");
            } /* end of action switch */
        } /* end of scanning one token */
    } /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer(void)
{
    char* dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
    char* source = (yytext_ptr);
    int number_to_move, i;
    int ret_val;

    if ((yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1])
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--end of buffer missed");

    if (YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0) { /* Don't try to fill the buffer, so this is an EOF. */
        if ((yy_c_buf_p) - (yytext_ptr)-YY_MORE_ADJ == 1) {
            /* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
            return EOB_ACT_END_OF_FILE;
        }

        else {
            /* We matched some text prior to the EOB, first
			 * process it.
			 */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int)((yy_c_buf_p) - (yytext_ptr)-1);

    for (i = 0; i < number_to_move; ++i)
        *(dest++) = *(source++);

    if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
        /* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

    else {
        int num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

        while (num_to_read <= 0) { /* Not enough room in the buffer - grow it. */

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

            int yy_c_buf_p_offset = (int)((yy_c_buf_p)-b->yy_ch_buf);

            if (b->yy_is_our_buffer) {
                int new_size = b->yy_buf_size * 2;

                if (new_size <= 0)
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char*)
                    /* Include room in for 2 EOB chars. */
                    yyrealloc((void*)b->yy_ch_buf,
                        (yy_size_t)(b->yy_buf_size + 2));
            } else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = NULL;

            if (!b->yy_ch_buf)
                YY_FATAL_ERROR(
                    "fatal error - scanner input buffer overflow");

            (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
        }

        if (num_to_read > YY_READ_BUF_SIZE)
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
            (yy_n_chars), num_to_read);

        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    if ((yy_n_chars) == 0) {
        if (number_to_move == YY_MORE_ADJ) {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart(yyin);
        }

        else {
            ret_val = EOB_ACT_LAST_MATCH;
            YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_EOF_PENDING;
        }
    }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
        /* Extend the array by 50%, plus the number we really need. */
        int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char*)yyrealloc(
            (void*)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t)new_size);
        if (!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
            YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
        /* "- 2" to take care of EOB's */
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int)(new_size - 2);
    }

    (yy_n_chars) += number_to_move;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

    (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

    return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state(void)
{
    yy_state_type yy_current_state;
    char* yy_cp;

    yy_current_state = (yy_start);

    for (yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp) {
        YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if (yy_accept[yy_current_state]) {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos) = yy_cp;
        }
        while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
            yy_current_state = (int)yy_def[yy_current_state];
            if (yy_current_state >= 74)
                yy_c = yy_meta[yy_c];
        }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    }

    return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state)
{
    int yy_is_jam;
    char* yy_cp = (yy_c_buf_p);

    YY_CHAR yy_c = 1;
    if (yy_accept[yy_current_state]) {
        (yy_last_accepting_state) = yy_current_state;
        (yy_last_accepting_cpos) = yy_cp;
    }
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
        yy_current_state = (int)yy_def[yy_current_state];
        if (yy_current_state >= 74)
            yy_c = yy_meta[yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 73);

    return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

static void yyunput(int c, char* yy_bp)
{
    char* yy_cp;

    yy_cp = (yy_c_buf_p);

    /* undo effects of setting up yytext */
    *yy_cp = (yy_hold_char);

    if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2) { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        int number_to_move = (yy_n_chars) + 2;
        char* dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
        char* source = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

        while (source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
            *--dest = *--source;

        yy_cp += (int)(dest - source);
        yy_bp += (int)(dest - source);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = (int)YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

        if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
            YY_FATAL_ERROR("flex scanner push-back overflow");
    }

    *--yy_cp = (char)c;

    (yytext_ptr) = yy_bp;
    (yy_hold_char) = *yy_cp;
    (yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void)
#else
static int input(void)
#endif

{
    int c;

    *(yy_c_buf_p) = (yy_hold_char);

    if (*(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR) {
        /* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
        if ((yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
            /* This was really a NUL. */
            *(yy_c_buf_p) = '\0';

        else { /* need more input */
            int offset = (int)((yy_c_buf_p) - (yytext_ptr));
            ++(yy_c_buf_p);

            switch (yy_get_next_buffer()) {
            case EOB_ACT_LAST_MATCH:
                /* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

                /* Reset buffer status. */
                yyrestart(yyin);

                /*FALLTHROUGH*/

            case EOB_ACT_END_OF_FILE: {
                if (yywrap())
                    return 0;

                if (!(yy_did_buffer_switch_on_eof))
                    YY_NEW_FILE;
#ifdef __cplusplus
                return yyinput();
#else
                return input();
#endif
            }

            case EOB_ACT_CONTINUE_SCAN:
                (yy_c_buf_p) = (yytext_ptr) + offset;
                break;
            }
        }
    }

    c = *(unsigned char*)(yy_c_buf_p); /* cast for 8-bit char's */
    *(yy_c_buf_p) = '\0'; /* preserve yytext */
    (yy_hold_char) = *++(yy_c_buf_p);

    return c;
}
#endif /* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyrestart(FILE* input_file)
{

    if (!YY_CURRENT_BUFFER) {
        yyensure_buffer_stack();
        YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
    }

    yy_init_buffer(YY_CURRENT_BUFFER, input_file);
    yy_load_buffer_state();
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
{

    /* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
    yyensure_buffer_stack();
    if (YY_CURRENT_BUFFER == new_buffer)
        return;

    if (YY_CURRENT_BUFFER) {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    YY_CURRENT_BUFFER_LVALUE = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
    (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state(void)
{
    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
    (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
    yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
    (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yy_create_buffer(FILE* file, int size)
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
    if (!b)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
    b->yy_ch_buf = (char*)yyalloc((yy_size_t)(b->yy_buf_size + 2));
    if (!b->yy_ch_buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_is_our_buffer = 1;

    yy_init_buffer(b, file);

    return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
void yy_delete_buffer(YY_BUFFER_STATE b)
{

    if (!b)
        return;

    if (b == YY_CURRENT_BUFFER) /* Not sure if we should pop here. */
        YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE)0;

    if (b->yy_is_our_buffer)
        yyfree((void*)b->yy_ch_buf);

    yyfree((void*)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
static void yy_init_buffer(YY_BUFFER_STATE b, FILE* file)

{
    int oerrno = errno;

    yy_flush_buffer(b);

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER) {
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

    b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;

    errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
void yy_flush_buffer(YY_BUFFER_STATE b)
{
    if (!b)
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if (b == YY_CURRENT_BUFFER)
        yy_load_buffer_state();
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state(YY_BUFFER_STATE new_buffer)
{
    if (new_buffer == NULL)
        return;

    yyensure_buffer_stack();

    /* This block is copied from yy_switch_to_buffer. */
    if (YY_CURRENT_BUFFER) {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    /* Only push if top exists. Otherwise, replace top. */
    if (YY_CURRENT_BUFFER)
        (yy_buffer_stack_top)++;
    YY_CURRENT_BUFFER_LVALUE = new_buffer;

    /* copied from yy_switch_to_buffer. */
    yy_load_buffer_state();
    (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state(void)
{
    if (!YY_CURRENT_BUFFER)
        return;

    yy_delete_buffer(YY_CURRENT_BUFFER);
    YY_CURRENT_BUFFER_LVALUE = NULL;
    if ((yy_buffer_stack_top) > 0)
        --(yy_buffer_stack_top);

    if (YY_CURRENT_BUFFER) {
        yy_load_buffer_state();
        (yy_did_buffer_switch_on_eof) = 1;
    }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack(void)
{
    yy_size_t num_to_alloc;

    if (!(yy_buffer_stack)) {

        /* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
        num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
        (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc(num_to_alloc * sizeof(struct yy_buffer_state*));
        if (!(yy_buffer_stack))
            YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

        memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

        (yy_buffer_stack_max) = num_to_alloc;
        (yy_buffer_stack_top) = 0;
        return;
    }

    if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {

        /* Increase the buffer to prepare for a possible push. */
        yy_size_t grow_size = 8 /* arbitrary grow size */;

        num_to_alloc = (yy_buffer_stack_max) + grow_size;
        (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc((yy_buffer_stack),
            num_to_alloc * sizeof(struct yy_buffer_state*));
        if (!(yy_buffer_stack))
            YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

        /* zero only the new slots.*/
        memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
        (yy_buffer_stack_max) = num_to_alloc;
    }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size)
{
    YY_BUFFER_STATE b;

    if (size < 2 || base[size - 2] != YY_END_OF_BUFFER_CHAR || base[size - 1] != YY_END_OF_BUFFER_CHAR)
        /* They forgot to leave room for the EOB's. */
        return NULL;

    b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
    if (!b)
        YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

    b->yy_buf_size = (int)(size - 2); /* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = NULL;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer(b);

    return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string(const char* yystr)
{

    return yy_scan_bytes(yystr, (int)strlen(yystr));
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes(const char* yybytes, int _yybytes_len)
{
    YY_BUFFER_STATE b;
    char* buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = (yy_size_t)(_yybytes_len + 2);
    buf = (char*)yyalloc(n);
    if (!buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

    for (i = 0; i < _yybytes_len; ++i)
        buf[i] = yybytes[i];

    buf[_yybytes_len] = buf[_yybytes_len + 1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer(buf, n);
    if (!b)
        YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

    /* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
    b->yy_is_our_buffer = 1;

    return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error(const char* msg)
{
    fprintf(stderr, "%s\n", msg);
    exit(YY_EXIT_FAILURE);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n)                                 \
    do {                                          \
        /* Undo effects of setting up yytext. */  \
        int yyless_macro_arg = (n);               \
        YY_LESS_LINENO(yyless_macro_arg);         \
        yytext[yyleng] = (yy_hold_char);          \
        (yy_c_buf_p) = yytext + yyless_macro_arg; \
        (yy_hold_char) = *(yy_c_buf_p);           \
        *(yy_c_buf_p) = '\0';                     \
        yyleng = yyless_macro_arg;                \
    } while (0)

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno(void)
{

    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE* yyget_in(void)
{
    return yyin;
}

/** Get the output stream.
 * 
 */
FILE* yyget_out(void)
{
    return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng(void)
{
    return yyleng;
}

/** Get the current token.
 * 
 */

char* yyget_text(void)
{
    return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno(int _line_number)
{

    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in(FILE* _in_str)
{
    yyin = _in_str;
}

void yyset_out(FILE* _out_str)
{
    yyout = _out_str;
}

int yyget_debug(void)
{
    return yy_flex_debug;
}

void yyset_debug(int _bdebug)
{
    yy_flex_debug = _bdebug;
}

static int yy_init_globals(void)
{
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy(void)
{

    /* Pop the buffer stack, destroying each element. */
    while (YY_CURRENT_BUFFER) {
        yy_delete_buffer(YY_CURRENT_BUFFER);
        YY_CURRENT_BUFFER_LVALUE = NULL;
        yypop_buffer_state();
    }

    /* Destroy the stack itself. */
    yyfree((yy_buffer_stack));
    (yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals();

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy(char* s1, const char* s2, int n)
{

    int i;
    for (i = 0; i < n; ++i)
        s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char* s)
{
    int n;
    for (n = 0; s[n]; ++n)
        ;

    return n;
}
#endif

void* yyalloc(yy_size_t size)
{
    return malloc(size);
}

void* yyrealloc(void* ptr, yy_size_t size)
{

    /* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
    return realloc(ptr, size);
}

void yyfree(void* ptr)
{
    free((char*)ptr); /* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 379 "lexer.l"

/*PROTO*/
#define NUMBER_PROGRAMS 10
#define MEMTOP 1024
#define MAXIMUM_LINES 2000

LINK* HashTable[PRIME]; /* My little hash table */
int DataLevel = 0; /* pointer within stack */
double DataStack[MEMTOP]; /* The data stack */
double* DataPtr;

int NextVal = 0; /* the  number of values to load directly
			     from the program */

double Memory[MEMTOP];

int LocalLevel = 0;
int CommandLevel = 0;
double* LocalStack;
int* CommandStack;

int CurrentLine = 0;
int CurrentProgram = 0;
double ProgramLocalStack[NUMBER_PROGRAMS][MAXIMUM_LINES];
int ProgramCommandStack[NUMBER_PROGRAMS][MAXIMUM_LINES];
int ProgramLevel[NUMBER_PROGRAMS];
int ProgramLocalLevel[NUMBER_PROGRAMS];

int PProgram = 0;
int PLevel = 0;
int PLLevel = 0;
int* PCStack = NULL;
double* PLStack = NULL;

int LabelLevel = 0;
ID* LabelStack[1000];

int SourceLevel = 0;
int SourceProgramStack[16];
int SourceLineStack[16];

/*START*/

/*BFUNC

initparser() is used to place the Reserved Words into the hash table.
It must be called before the parser command is called.

EFUNC*/

void initparser()
{
    char i, **sptr;
    BEGIN NORMAL;

    for (i = 1, sptr = ReservedWords; **sptr != '\0'; i++, sptr++) { /* Add Reserved Words */
        enter(i, *sptr, strlen(*sptr));
    }
    for (i = 1, sptr = EquLabels; **sptr != '\0'; i++, sptr++) { /* Add defined labels */
        equname(i, *sptr);
    }
    for (i = 0; i < NUMBER_PROGRAMS; i++) {
        ProgramLevel[i] = 0;
    }
    DataLevel = 0;
    DataPtr = DataStack;
}

#undef BEGIN
#undef MakeStructure
#include "globals.h"
#include "stream.h"
#include <math.h>

#define pushdata(val)             \
    *(DataPtr++) = (double)(val); \
    DataLevel++;

extern FRAME* CFrame;
extern IMAGE* CImage;
extern int ErrorValue;
extern int FrameRate;
extern int FrameRateDiv;
extern int FrameSkip;
extern int SearchLimit;
extern int ImageType;
extern int InitialQuant;

/*BFUNC

hashpjw() returns a hash value for a string input.

EFUNC*/

static int hashpjw(s) char* s;
{
    BEGIN("hashpjw");
    char* p;
    unsigned int h = 0, g;

    for (p = s; *p != EOS; p++) {
        h = (h << 4) + *p;
        if (g = h & 0xf0000000) {
            h = h ^ (g >> 24);
            h = h ^ g;
        }
    }
    return (h % PRIME);
}

/*BFUNC

MakeLink() is used to construct a link object. The link
is used for the hash table construct.

EFUNC*/

static LINK* MakeLink(tokentype, str, len) int tokentype;
char* str;
int len;
{
    BEGIN("MakeLink");
    LINK* temp;

    if (!(temp = MakeStructure(LINK))) {
        WHEREAMI();
        printf("Cannot make a LINK.\n");
        exit(ERROR_MEMORY);
    }
    if (!(temp->lid = MakeStructure(ID))) {
        printf("Cannot make an id.\n");
        exit(ERROR_MEMORY);
    }
    temp->next = NULL;
    if (!(temp->lid->name = (char*)calloc(len + 1, sizeof(char)))) {
        printf("Cannot make a string space for the link.\n");
        exit(ERROR_MEMORY);
    }
    strcpy(temp->lid->name, str);
    temp->lid->tokentype = tokentype;
    temp->lid->count = 1;
    temp->lid->value = -1; /* Unreferenced yet. */
    return (temp);
}

/*BFUNC

enter() is used to enter a Reserved Word or ID into the hash table.

EFUNC*/

static ID* enter(tokentype, str, len) int tokentype;
char* str;
int len;
{
    BEGIN("enter");
    int hashnum;
    LINK *temp, *current;
    char* ptr;

    for (ptr = str; *ptr != '\0'; ptr++) {
        if ((*ptr >= 'a') && (*ptr <= 'z')) {
            *ptr = *ptr - ('a' - 'A');
        }
    }
    hashnum = hashpjw(str); /* Check if in hash table */
    for (temp = NULL, current = HashTable[hashnum];
         current != NULL;
         current = current->next) {
        if (strcmp(str, current->lid->name) == 0) {
            temp = current;
            break;
        }
    }
    if (temp) /* Yes, found ID then return */
    {
        temp->lid->count++;
        return (temp->lid);
    } else /* Else make our own ID and return that*/
    {
        temp = MakeLink(tokentype, str, len);
        InsertLink(temp, HashTable[hashnum]);
        return (temp->lid);
    }
}

equname(number, name) int number;
char* name;
{
    ID* temp;
    temp = enter(0, name, strlen(name));
    temp->value = number;
}

/*BFUNC

getstr() gets a string from the input. It copies the string to
temporary storage before it returns the pointer.

EFUNC*/

static char* getstr()
{
    BEGIN("getstr");
    char *tmp, *ptr, *bptr;
    int i, accum, flag;
    if (mylex() != R_STRING) {
        printf("String expected.\n");
        if (!(tmp = (char*)malloc(sizeof(char)))) {
            WHEREAMI();
            printf("Cannot allocate for null string.\n");
            exit(ERROR_MEMORY);
        }
        *tmp = '\0';
        return (tmp);
    }
    if (!(tmp = (char*)calloc(strlen(yytext) + 1, sizeof(char)))) {
        WHEREAMI();
        printf("Cannot allocate %d string space.\n", yyleng);
        exit(ERROR_MEMORY);
    }
    for (bptr = yytext + 1, ptr = tmp; *bptr != '"'; bptr++, ptr++) {
        if (*bptr == '\\') {
            bptr++;
            for (flag = 0, accum = 0, i = 0; i < 3; i++) /* Octal character lookahead */
            {
                if ((*bptr >= '0') && (*bptr <= '7')) {
                    accum = (accum << 3) + (*bptr - '0');
                    bptr++;
                    flag = 1;
                } else {
                    break;
                }
            }
            if (flag) {
                bptr--;
                *ptr = accum;
            } else {
                switch (*(bptr)) {
                case '0':
                    *ptr = 0;
                    break;
                case 'b':
                    *ptr = 0x8;
                    break;
                case 'i':
                    *ptr = 0x9;
                    break;
                case 'n':
                    *ptr = 0xa;
                    break;
                case 'v':
                    *ptr = 0xb;
                    break;
                case 'f':
                    *ptr = 0xc;
                    break;
                case 'r':
                    *ptr = 0xd;
                    break;
                default:
                    *ptr = (*bptr);
                }
            }
        } else {
            *ptr = (*bptr);
        }
    }
    *ptr = '\0';
    return (tmp);
}

/*BFUNC

parser() handles all of the parsing required for the Program
Interpreter.  It is basically a {\tt while} statement with a very
large case statement for every input.  All unmatched values-- strings,
brackets, etc. are ignored.

EFUNC*/

#define ARRAYBEGIN                     \
    if (ntoken == R_LBRACKET) {        \
        arrayflag = 1;                 \
        ntoken = mylex();              \
    }                                  \
    if (ntoken != R_INTEGER) {         \
        WHEREAMI();                    \
        printf("Expected integer.\n"); \
        break;                         \
    }                                  \
    while (1) {

#define ARRAYEND                                            \
    if (arrayflag) {                                        \
        if ((ntoken = mylex()) == R_RBRACKET)               \
            break;                                          \
        else if (ntoken != R_INTEGER) {                     \
            WHEREAMI();                                     \
            printf("Expected integer or right bracket.\n"); \
            break;                                          \
        }                                                   \
    } else                                                  \
        break;                                              \
    }

#define BINARYOP(operation)                        \
    if (DataLevel < 2) {                           \
        printf("Not enough operands on stack.\n"); \
        break;                                     \
    }                                              \
    accum = *(--DataPtr);                          \
    *(--DataPtr)operation accum;                   \
    DataPtr++;                                     \
    DataLevel--;

#define RELOP(operation)                           \
    if (DataLevel < 2) {                           \
        printf("Not enough operands on stack.\n"); \
        break;                                     \
    }                                              \
    accum = *(--DataPtr);                          \
    DataPtr--;                                     \
    if (*(DataPtr)operation(accum))                \
        *(DataPtr++) = 1.0;                        \
    else                                           \
        *(DataPtr++) = 0.0;                        \
    DataLevel--;

#define openprogram(value)                  \
    PProgram = (value);                     \
    PLStack = ProgramLocalStack[(value)];   \
    PCStack = ProgramCommandStack[(value)]; \
    PLLevel = ProgramLocalLevel[(value)];   \
    PLevel = ProgramLevel[(value)];

#define pushprogram(program, line)                      \
    SourceProgramStack[SourceLevel] = CurrentProgram;   \
    SourceLineStack[SourceLevel] = CurrentLine;         \
    SourceLevel++;                                      \
    CurrentProgram = program;                           \
    CurrentLine = line;                                 \
    CommandStack = ProgramCommandStack[CurrentProgram]; \
    LocalStack = ProgramLocalStack[CurrentProgram];     \
    LocalLevel = ProgramLocalLevel[CurrentProgram];     \
    CommandLevel = ProgramLevel[CurrentProgram];

#define popprogram()                                    \
    SourceLevel--;                                      \
    CurrentProgram = SourceProgramStack[SourceLevel];   \
    CurrentLine = SourceLineStack[SourceLevel];         \
    CommandStack = ProgramCommandStack[CurrentProgram]; \
    LocalStack = ProgramLocalStack[CurrentProgram];     \
    LocalLevel = ProgramLocalLevel[CurrentProgram];     \
    CommandLevel = ProgramLevel[CurrentProgram];

#define GETINTEGER(retval)             \
    (retval) = mylex();                \
    if ((retval) != R_INTEGER) {       \
        WHEREAMI();                    \
        printf("Integer expected.\n"); \
        break;                         \
    }

void parser()
{
    BEGIN("parser");
    int i, dest, value, token, ntoken, arrayflag;
    double accum;
    int hold;
    char* sptr;

    while (token = mylex()) {
        arrayflag = 0;
        switch (token) {
        case R_INTEGER:
            pushdata((double)yyint);
            break;
        case R_REAL:
            pushdata(atof(yytext));
            break;

        case R_ADD:
            BINARYOP(+=);
            break;
        case R_SUB:
            BINARYOP(-=);
            break;
        case R_MUL:
            BINARYOP(*=);
            break;
        case R_DIV:
            BINARYOP(/=);
            break;
        case R_NOT:
            accum = *(--DataPtr);
            *(DataPtr++) = (accum ? 0.0 : 1.0);
            break;
        case R_AND:
            RELOP(&&);
            break;
        case R_OR:
            RELOP(||);
            break;
        case R_XOR:
            if (DataLevel < 2) {
                printf("Not enough operands on stack.\n");
                break;
            }
            accum = *(--DataPtr);
            DataPtr--;
            if ((*(DataPtr) && !(accum)) || (!(*(DataPtr)) && (accum)))
                *(DataPtr++) = 1.0;
            else
                *(DataPtr++) = 0.0;
            DataLevel--;
            break;
        case R_LT:
            RELOP(<);
            break;
        case R_LTE:
            RELOP(<=);
            break;
        case R_EQ:
            RELOP(==);
            break;
        case R_GT:
            RELOP(>);
            break;
        case R_GTE:
            RELOP(>=);
            break;

        case R_NEG:
            accum = *(--DataPtr);
            *(DataPtr++) = -(accum);
            break;
        case R_SQRT:
            accum = *(--DataPtr);
            *(DataPtr++) = sqrt(accum);
            break;
        case R_ABS:
            accum = *(--DataPtr);
            *(DataPtr++) = fabs(accum);
            break;
        case R_FLOOR:
            accum = *(--DataPtr);
            *(DataPtr++) = floor(accum);
            break;
        case R_CEIL:
            accum = *(--DataPtr);
            *(DataPtr++) = ceil(accum);
            break;
        case R_ROUND:
            accum = *(--DataPtr);
            *(DataPtr++) = ((accum < 0) ? ceil(accum - 0.5) : floor(accum + 0.5));
            break;

        case R_DUP:
            *(DataPtr++) = DataPtr[-1];
            DataLevel++;
            break;
        case R_POP:
            if (DataLevel) {
                DataLevel--;
                DataPtr--;
            } else {
                printf("Not enough stack elements.\n");
            }
            break;
        case R_EXCH:
            *DataPtr = DataPtr[-1];
            DataPtr[-1] = DataPtr[-2];
            DataPtr[-2] = *DataPtr;
            break;
        case R_COPY:
            GETINTEGER(ntoken);
            if (DataLevel < yyint) {
                WHEREAMI();
                printf("Not enough elements\n");
                break;
            }
            for (i = 0; i < yyint; i++) {
                *(DataPtr) = DataPtr[-yyint];
                DataPtr++;
                DataLevel++;
            }
            break;
        case R_ROLL:
            GETINTEGER(ntoken);
            dest = yyint;
            GETINTEGER(ntoken);
            value = yyint;
            value = value % dest;
            if (value < 0) {
                value += dest;
            }
            for (i = 0; i < value; i++) {
                DataPtr[i] = DataPtr[i - value];
            }
            for (i = 0; i < dest - value; i++) {
                DataPtr[-i - 1] = DataPtr[-value - i - 1];
            }
            for (i = 0; i < value; i++) {
                DataPtr[i - dest] = DataPtr[i];
            }
            break;
        case R_INDEX:
            GETINTEGER(ntoken);
            if (yyint > DataLevel) {
                WHEREAMI();
                printf("Index out of bounds\n");
                break;
            }
            *DataPtr = DataPtr[-yyint];
            DataPtr++;
            DataLevel++;
            break;
        case R_CLEAR:
            DataLevel = 0;
            DataPtr = DataStack;
            break;

        case R_STO:
            if (!DataLevel) {
                printf("Not enough stack elements.\n");
            }
            ntoken = mylex();
            if ((ntoken != R_ID) && (ntoken != R_INTEGER)) {
                printf("Integer or label expected.\n");
                break;
            }
            Memory[yyint] = *(--DataPtr);
            DataLevel--;
            break;
        case R_RCL:
            ntoken = mylex();
            if ((ntoken != R_ID) && (ntoken != R_INTEGER)) {
                printf("Integer or label expected.\n");
                break;
            }
            pushdata(Memory[yyint]);
            break;

        case R_GOTO:
        case R_IFG:
        case R_IFNG:
        case R_EXIT:
            WHEREAMI();
            printf("Program commands not available on top-level.\n");
            break;

        case R_EXE:
            ntoken = mylex();
            if ((ntoken != R_ID) && (ntoken != R_INTEGER)) {
                printf("Integer or label expected.\n");
                break;
            }
            pushprogram(yyint, 0);
            break;
        case R_ABORT:
            GETINTEGER(ntoken);
            exit(yyint);
            break;

        case R_PRINTSTACK:
            for (i = 0; i < DataLevel; i++) {
                printf("%d: %f\n", i, DataStack[i]);
            }
            break;
        case R_PRINTPROGRAM:
            ntoken = mylex();
            if ((ntoken != R_ID) && (ntoken != R_INTEGER)) {
                printf("Integer or label expected.\n");
                break;
            }
            openprogram(yyint);
            PrintProgram();
            break;
        case R_PRINTIMAGE:
            PrintImage();
            break;
        case R_PRINTFRAME:
            PrintFrame();
            break;

        case R_ECHO:
            printf("%s\n", getstr());
            break;
        case R_OPEN:
            ntoken = mylex();
            if ((ntoken != R_ID) && (ntoken != R_INTEGER)) {
                printf("Integer or label expected.\n");
                break;
            }
            hold = yyint;
            openprogram(hold);
            PLevel = 0;
            MakeProgram();
            CompileProgram();
            ProgramLevel[hold] = PLevel;
            ProgramLocalLevel[hold] = PLLevel;
            break;
        case R_CLOSE:
            WHEREAMI();
            printf("Close not available on top level.\n");
            break;

        case R_EQU:
            if (!DataLevel) {
                printf("Not enough stack elements.\n");
            }
            ntoken = mylex();
            if ((ntoken != R_ID)) {
                printf("Label expected.\n");
                break;
            }
            Cid->value = (int)*(--DataPtr);
            DataLevel--;
            break;
        case R_VAL:
            WHEREAMI();
            printf("VAL is not a valid id on top level.\n");
            break;

        case R_STREAMNAME:
            CImage->StreamFileName = getstr();
            break;
        case R_COMPONENT:
            ntoken = mylex();
            ARRAYBEGIN;
            dest = yyint;
            ntoken = mylex();
            if (ntoken != R_LBRACKET) {
                WHEREAMI();
                printf("Left bracket expected.\n");
                break;
            }
            sptr = getstr();
            strcpy(CFrame->ComponentFilePrefix[dest], sptr);
            sptr = getstr();
            strcpy(CFrame->ComponentFileSuffix[dest], sptr);
            ntoken = mylex();
            if (ntoken != R_RBRACKET) {
                WHEREAMI();
                printf("Right bracket expected.\n");
                break;
            }
            ARRAYEND;
            break;
        case R_FRAMERATE:
            GETINTEGER(ntoken);
            FrameRate = yyint;
            FrameRateDiv = 1;
            break;
        case R_FRAMESKIP:
            GETINTEGER(ntoken);
            FrameSkip = yyint;
            break;
        case R_QUANTIZATION:
            GETINTEGER(ntoken);
            InitialQuant = yyint;
            break;
        case R_SEARCHLIMIT:
            GETINTEGER(ntoken);
            SearchLimit = yyint;
            BoundValue(SearchLimit, 1, 31, "SearchLimit");
            break;
        case R_NTSC:
            ImageType = IT_NTSC;
            break;
        case R_CIF:
            ImageType = IT_CIF;
            break;
        case R_QCIF:
            ImageType = IT_QCIF;
            break;
        default:
            WHEREAMI();
            printf("Illegal token type encountered: %d\n", token);
            break;
        }
    }
}

/*BFUNC

PrintProgram() prints out a program that is loaded as current.

EFUNC*/

static void PrintProgram()
{
    BEGIN("PrintProgram");
    int i;

    for (i = 0; i < PLevel; i++) {
        switch (PCStack[i]) {
        case R_ADD:
        case R_SUB:
        case R_MUL:
        case R_DIV:

        case R_NOT:
        case R_AND:
        case R_OR:
        case R_XOR:
        case R_LT:
        case R_LTE:
        case R_EQ:
        case R_GT:
        case R_GTE:

        case R_NEG:
        case R_SQRT:
        case R_ABS:
        case R_FLOOR:
        case R_CEIL:
        case R_ROUND:

        case R_DUP:
        case R_POP:
        case R_EXCH:
        case R_CLEAR:
        case R_EXIT:
        case R_PRINTSTACK:
        case R_PRINTIMAGE:
        case R_PRINTFRAME:
            printf("%d: %s\n",
                i,
                ReservedWords[PCStack[i] - 1]);
            break;
        case R_COPY:
        case R_INDEX:
        case R_STO:
        case R_RCL:
        case R_EXE:
        case R_ABORT:
        case R_PRINTPROGRAM:
            printf("%d: %s %d\n",
                i,
                ReservedWords[PCStack[i] - 1],
                PCStack[i + 1]);
            i++;
            break;
        case R_ROLL:
            printf("%d: %s %d %d\n",
                i,
                ReservedWords[PCStack[i] - 1],
                PCStack[i + 1],
                PCStack[i + 2]);
            i += 2;
            break;
        case R_GOTO:
        case R_IFG:
        case R_IFNG:
            printf("%d: %s %d\n",
                i,
                ReservedWords[PCStack[i] - 1],
                PCStack[i + 1]);
            i++;
            break;
        case R_VAL:
            printf("%d: %s %f\n",
                i,
                ReservedWords[PCStack[i] - 1],
                PLStack[PCStack[i + 1]]);
            i++;
            break;
        case R_ECHO:
        case R_OPEN:
        case R_CLOSE:
        case R_EQU:
        case R_STREAMNAME:
        case R_COMPONENT:
        case R_FRAMERATE:
        case R_FRAMESKIP:
        case R_QUANTIZATION:
        case R_SEARCHLIMIT:
        case R_NTSC:
        case R_CIF:
        case R_QCIF:
            WHEREAMI();
            printf("Top-level token occurring in program: %s.\n",
                ReservedWords[PCStack[i] - 1]);
            break;
        default:
            WHEREAMI();
            printf("Bad token type %d\n", PCStack[i]);
            break;
        }
    }
}

/*BFUNC

MakeProgram() makes a program from the input from mylex().

EFUNC*/

static void MakeProgram()
{
    BEGIN("MakeProgram");
    int ntoken;

    while ((ntoken = mylex()) != R_CLOSE) {
        switch (ntoken) {
        case 0:
            exit(-1);
            break;
        case R_ADD:
        case R_SUB:
        case R_MUL:
        case R_DIV:

        case R_NOT:
        case R_AND:
        case R_OR:
        case R_XOR:
        case R_LT:
        case R_LTE:
        case R_EQ:
        case R_GT:
        case R_GTE:

        case R_NEG:
        case R_SQRT:
        case R_ABS:
        case R_FLOOR:
        case R_CEIL:
        case R_ROUND:

        case R_DUP:
        case R_POP:
        case R_EXCH:
        case R_CLEAR:

        case R_EXIT:
        case R_PRINTSTACK:
        case R_PRINTIMAGE:
        case R_PRINTFRAME:
            PCStack[PLevel++] = ntoken;
            break;
        case R_COPY:
        case R_INDEX:
        case R_STO:
        case R_RCL:
        case R_EXE:
        case R_ABORT:
        case R_PRINTPROGRAM:
            PCStack[PLevel++] = ntoken;
            ntoken = mylex();
            if ((ntoken == R_INTEGER) || (ntoken == R_ID)) {
                PCStack[PLevel++] = yyint;
            } else {
                PCStack[PLevel++] = 0;
                printf("Integer expected.\n");
            }
            break;
        case R_ROLL:
            PCStack[PLevel++] = ntoken;
            ntoken = mylex();
            if ((ntoken == R_INTEGER) || (ntoken == R_ID)) {
                PCStack[PLevel++] = yyint;
            } else {
                PCStack[PLevel++] = 0;
                printf("Integer expected.\n");
            }
            ntoken = mylex();
            if ((ntoken == R_INTEGER) || (ntoken == R_ID)) {
                PCStack[PLevel++] = yyint;
            } else {
                PCStack[PLevel++] = 0;
                printf("Integer expected.\n");
            }
            break;
        case R_GOTO:
        case R_IFG:
        case R_IFNG:
            PCStack[PLevel++] = ntoken;
            ntoken = mylex();
            if (ntoken == R_ID) {
                LabelStack[LabelLevel] = Cid;
                PCStack[PLevel++] = LabelLevel++;
            } else {
                printf("Id expected.\n");
            }
            break;
        case R_VAL:
            PCStack[PLevel++] = ntoken;
            PLStack[PLLevel] = (double)*(--DataPtr); /* Take from Top of stack */
            DataLevel--;
            PCStack[PLevel++] = PLLevel++;
            break;
        case R_INTEGER:
            PCStack[PLevel++] = R_VAL;
            PLStack[PLLevel] = (double)yyint;
            PCStack[PLevel++] = PLLevel++;
            break;
        case R_REAL:
            PCStack[PLevel++] = R_VAL;
            PLStack[PLLevel] = atof(yytext);
            PCStack[PLevel++] = PLLevel++;
            break;
        case R_ID:
            if (Cid->value >= 0) {
                WHEREAMI();
                printf("Attempt to redefine label.\n");
                break;
            }
            Cid->value = PLevel;
            break;
        default:
            WHEREAMI();
            printf("Token type %d not allowed in programs.\n", ntoken);
            break;
        }
    }
}

/*BFUNC

CompileProgram() assigns values to the labels in a program.

EFUNC*/

static void CompileProgram()
{
    BEGIN("CompileProgram");
    int i;

    for (i = 0; i < PLevel; i++) {
        switch (PCStack[i]) {
        case R_ADD:
        case R_SUB:
        case R_MUL:
        case R_DIV:

        case R_NOT:
        case R_AND:
        case R_OR:
        case R_XOR:
        case R_LT:
        case R_LTE:
        case R_EQ:
        case R_GT:
        case R_GTE:

        case R_NEG:
        case R_SQRT:
        case R_ABS:
        case R_FLOOR:
        case R_CEIL:
        case R_ROUND:

        case R_DUP:
        case R_POP:
        case R_EXCH:
        case R_CLEAR:

        case R_EXIT:
        case R_PRINTSTACK:
        case R_PRINTIMAGE:
        case R_PRINTFRAME:
            break;
        case R_COPY:
        case R_INDEX:
        case R_STO:
        case R_RCL:
        case R_EXE:
        case R_ABORT:
        case R_VAL:
        case R_PRINTPROGRAM:
            i++;
            break;
        case R_ROLL:
            i += 2;
            break;
        case R_GOTO:
        case R_IFG:
        case R_IFNG:
            i++;
            if (!LabelStack[PCStack[i]]->value) {
                printf("Bad reference to label!\n");
                break;
            }
            PCStack[i] = LabelStack[PCStack[i]]->value;
            break;
        default:
            WHEREAMI();
            printf("Invalid program compilation token: %d.\n", PCStack[i]);
            break;
        }
    }
}

/*BFUNC

mylex() reads either from the yylex() routine or from the currently
active program depending on what source is active.

EFUNC*/

static int mylex()
{
    BEGIN("mylex");
    int token;

    while (1) {
        if (!SourceLevel) {
            return (yylex());
        }
        token = CommandStack[CurrentLine++];
        /*
      printf("Token:%d  CommandStack:%x  CurrentLine:%d\n",
	     token,CommandStack,CurrentLine-1);
*/
        if (NextVal) {
            NextVal--;
            yyint = token;
            return (R_INTEGER);
        }
        switch (token) {
        case 0:
            printf("Abnormal break at: %d\n", CurrentLine);
            popprogram();
            break;
        case R_VAL:
            pushdata(LocalStack[CommandStack[CurrentLine++]]);
            break;
        case R_GOTO:
            CurrentLine = CommandStack[CurrentLine];
            break;
        case R_IFG:
            DataLevel--;
            if (*(--DataPtr)) {
                CurrentLine = CommandStack[CurrentLine];
            } else
                CurrentLine++;
            break;
        case R_IFNG:
            DataLevel--;
            if (!(*(--DataPtr))) {
                CurrentLine = CommandStack[CurrentLine];
            } else
                CurrentLine++;
            break;
        case R_EXIT:
            popprogram();
            break;
        case R_COPY:
        case R_INDEX:
        case R_STO:
        case R_RCL:
        case R_EXE:
        case R_ABORT:
        case R_PRINTPROGRAM:
            NextVal = 1; /* Notify to take the next integer straight */
            return (token);
            break;
        case R_ROLL:
            NextVal = 2;
            return (token);
            break;
        default:
            return (token);
            break;
        }
    }
}

/*BFUNC

Execute() calls the program interpreter to execute a particular
program location.

EFUNC*/

void Execute(pnum) int pnum;
{
    BEGIN("Execute");

    if (ProgramLevel[pnum]) {
        pushprogram(pnum, 0);
        parser();
    }
}

/*NOPROTO*/
/*END*/
